
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    platform: linux/amd64 # Arm
    ports:
      - '2181:2181'
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    platform: linux/amd64 # Arm
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_OFFSETS_RETENTION_MINUTES: 10080
    depends_on:
      - zookeeper
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    platform: linux/arm64/v8 # Arm
    ports:
      - '6379:6379'
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}


